Add netdata to metrics services
Forestscribe/marathon-ansible pull request #2
Opened 2017-03-15 12:33 UTC by bastien31

Create one netdata instances per worker.

Signed-off-by: Sebastien Fusilier <sebastien.fusilier@gmail.com>

2017-03-15 14:46 UTC, tardyp commented on marathon/core/metrics.yml
> +                    - containerPort: 19999
I think we want to map this to a host port instead of service port. 
Do we need a registry docker, this one shall  be mapped on the nixy

2017-03-28 13:54 UTC, tardyp requested changes

2017-03-28 13:54 UTC, tardyp commented on marathon/gitlab/runners.yml
> +              - containerPath: "/var/run/docker.sock"
please add comment why

2017-03-28 13:54 UTC, tardyp commented on marathon/gitlab/runners.yml
> +                REGISTRATION_TOKEN: 4y5UzT4XoXUibU147zzQ
please dont put tokens here.
please put them in the ansible vault

2017-03-28 13:54 UTC, tardyp commented on marathon/gitlab/runners.yml
> +            # healthChecks:
remove comments

2017-03-28 13:54 UTC, tardyp commented on marathon/gitlab/master.yml
> +              # subdomain: '/gitlab'
I guess that is needed

2017-03-28 13:54 UTC, tardyp commented on marathon/gitlab/master.yml
> +            env:
we really need all those envs?

please keep only the needed one, and rather point to the list of available and default

2017-03-28 13:54 UTC, tardyp commented on marathon/gitlab/core.yml
> +                DB_PASS: password
needs to be in ansible vault

2017-03-28 13:54 UTC, tardyp commented on marathon/gitlab.yml
> +    # - include: "gitlab/core.yml"
commented?

2017-03-28 14:32 UTC, bastien31 commented
My mistake, all gitlab stuff shall not be in that PR.

2017-03-28 14:32 UTC, closed without merging