Traefik, Airflow, OpenWhisk
Forestscribe/marathon-ansible pull request #4
Opened 2017-04-27 15:53 UTC by Stibbons

2017-04-27 16:05 UTC, tardyp requested changes

2017-04-27 16:05 UTC, tardyp commented on README.md
> +    export DOMAIN_EXT=<domainserver.ext>
put this is the vault

2017-04-27 16:05 UTC, tardyp commented on group_vars/all
> +domain_ext: "{{ ansible_env.DOMAIN_EXT }}"
```
+domain_ext: "{{ zk.cloud.DOMAIN_EXT }}
```

2017-04-27 16:05 UTC, tardyp commented on marathon/airflow/celery.yml
> +            FRENET_KEY: AFKp0LrregZGOucp22eOr0jW0Ru2PmbZzBWoeCdL8Vk=
change and put in the zk vault

2017-04-28 08:03 UTC, tardyp requested changes

2017-04-28 08:03 UTC, tardyp commented on marathon/airflow/celery.yml
> +            http_proxy: http://proxy-ir.{{ domain_ext }}:911
there are already proxy config
```
                https_proxy: "{{zk.proxy_env.https_proxy}}"
                http_proxy: "{{zk.proxy_env.http_proxy}}"
                no_proxy: "{{zk.proxy_env.no_proxy}}"
                ALL_PROXY: "{{zk.proxy_env.ALL_PROXY}}"
```

2017-04-28 08:03 UTC, tardyp commented on marathon/airflow/celery.yml
> +              - containerPath: "airflowdags"
this really needs to be stored here?
This shall be stored on git right?

2017-04-28 08:03 UTC, tardyp commented on marathon/core/traefik.yml
> +                      hostPort: 80
don't put hostPort if network is bridge

2017-04-28 08:03 UTC, tardyp commented on marathon/core/traefik.yml
> +                      servicePort: "{{ servicePorts.traefik_admin }}"
I think this should got to traefik.forestscribe.xxx.com

2017-04-28 08:03 UTC, tardyp commented on marathon/core/traefik.yml
> +                http_proxy: http://proxy-ir.{{ domain_ext }}:911
use zk config

2017-04-28 08:03 UTC, tardyp commented on marathon/core/traefik.yml
> +                subdomain: 't'
why not put subdomain to forestscribe?

2017-05-02 09:09 UTC, Stibbons commented on README.md
> +    export DOMAIN_EXT=<domainserver.ext>
done

2017-05-02 09:16 UTC, Stibbons commented on marathon/airflow/celery.yml
> +            FRENET_KEY: AFKp0LrregZGOucp22eOr0jW0Ru2PmbZzBWoeCdL8Vk=
done

2017-05-02 09:16 UTC, Stibbons commented on marathon/airflow/celery.yml
> +              - containerPath: "airflowdags"
maybe a shared volume ?

2017-05-02 09:20 UTC, Stibbons commented on marathon/airflow/celery.yml
> +            http_proxy: http://proxy-ir.{{ domain_ext }}:911
done

2017-05-02 09:21 UTC, Stibbons commented on marathon/core/traefik.yml
> +                      hostPort: 80
needed to force to take the port 80 (it's it the entrypoint for routing) and have the URL in the marathon ui with the right port.

2017-05-02 09:22 UTC, Stibbons commented on marathon/core/traefik.yml
> +                      servicePort: "{{ servicePorts.traefik_admin }}"
it can do it, just need to deal with the port that is not 80

2017-05-02 09:23 UTC, Stibbons commented on marathon/core/traefik.yml
> +                http_proxy: http://proxy-ir.{{ domain_ext }}:911
done

2017-05-02 09:23 UTC, Stibbons commented on marathon/core/traefik.yml
> +                subdomain: 't'
done

2017-05-02 15:31 UTC, tardyp commented on marathon/airflow/celery.yml
> +              - containerPath: "airflowdags"
with buildbot, we have a http clone from github to load the master.cfg

2017-05-02 15:32 UTC, tardyp commented on marathon/core/traefik.yml
> +                      hostPort: 80
user host mode

2017-05-02 15:32 UTC, tardyp commented
looks like you said done, but you didn't push

2017-05-03 11:15 UTC, merged